[package]
name = "rust_sandbox"
version = "0.1.0"
authors = ["Nivas Muthu M G <nivasmuthu452@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
